rollback

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -12,36 +12,36 @@ jobs:
     
     runs-on: ubuntu-latest
   
-    services:
-      mariadb:
-        image: mariadb:10.4
-        env:
-          MYSQL_ROOT_PASSWORD: teslalogger
-          MYSQL_DATABASE: teslalogger
-          MYSQL_USER: teslalogger
-          MYSQL_PASSWORD: teslalogger
-        ports:
-          - 3306:3306
-        options: >-
-          --health-cmd="mysqladmin ping --silent"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=3
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      with:
-        sparse-checkout: |
-          TeslaLogger/sqlschema.sql
-
-    - name: Wait for MariaDB to be healthy
-      run: |
-        while ! mysqladmin ping -h"127.0.0.1" --silent; do
-          sleep 1
-        done
-
-    - name: Run SQL script
-      run: mysql -h127.0.0.1 -uroot -pteslalogger -Dteslalogger < TeslaLogger/sqlschema.sql
+    #services:
+    #  mariadb:
+    #    image: mariadb:10.4
+    #    env:
+    #      MYSQL_ROOT_PASSWORD: teslalogger
+    #      MYSQL_DATABASE: teslalogger
+    #      MYSQL_USER: teslalogger
+    #      MYSQL_PASSWORD: teslalogger
+    #    ports:
+    #      - 3306:3306
+    #    options: >-
+    #      --health-cmd="mysqladmin ping --silent"
+    #      --health-interval=10s
+    #      --health-timeout=5s
+    #      --health-retries=3
+    #steps:
+    #- name: Checkout
+    #  uses: actions/checkout@v3
+    #  with:
+    #    sparse-checkout: |
+    #      TeslaLogger/sqlschema.sql
+#
+    #- name: Wait for MariaDB to be healthy
+    #  run: |
+    #    while ! mysqladmin ping -h"127.0.0.1" --silent; do
+    #      sleep 1
+    #    done
+#
+    #- name: Run SQL script
+    #  run: mysql -h127.0.0.1 -uroot -pteslalogger -Dteslalogger < TeslaLogger/sqlschema.sql
 
 
 
@@ -73,8 +73,8 @@ jobs:
     - name: Restore nuget packages
       run: nuget restore TeslaLogger.sln
 
-    - name: ping
-      run: ping mariadb
+    #- name: ping
+    #  run: ping mariadb
     
     - name: Build solution
       run: msbuild TeslaLogger.sln -t:rebuild -property:Configuration=Debug
